#如果你的终端支持ANSI，设置彩色输出会让日志更具可读性。
#NEVER：禁用ANSI-colored输出（默认项）
#DETECT：会检查终端是否支持ANSI，是的话就采用彩色输出（推荐项）
#ALWAYS：总是使用ANSI-colored格式输出，若终端不支持的时候，会有很多干扰信息，不推荐使用
spring:
  profiles:
    active: t
  output:
    ansi:
      enabled: detect

banner:
  charset: utf-8
  location: banner.txt

logging:
  config: classpath:log4j2.xml

endpoints:
  shutdown:
    enabled: true

